import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import FinancialOverview from "@/components/dashboard/FinancialOverview";
import GoalsSection from "@/components/dashboard/GoalsSection";
import AIInsights from "@/components/dashboard/AIInsights";
import TransactionHistory from "@/components/dashboard/TransactionHistory";
import { MessageSquare, Settings, Plus } from "lucide-react";
import { useNavigate } from "react-router-dom";

const Dashboard = () => {
  const navigate = useNavigate();
  const [userName] = useState("Rahul");

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-card/80 backdrop-blur-lg border-b border-border shadow-sm">
        <div className="container mx-auto px-4 py-4 flex justify-between items-center">
          <div>
            <h1 className="text-2xl font-display font-bold bg-gradient-primary bg-clip-text text-transparent">
              MuneemAI
            </h1>
            <p className="text-sm text-muted-foreground">Namaste, {userName}! 👋</p>
          </div>
          <div className="flex gap-2">
            <Button
              variant="ghost"
              size="icon"
              onClick={() => navigate("/chat")}
              className="transition-smooth hover:scale-105"
            >
              <MessageSquare className="h-5 w-5" />
            </Button>
            <Button
              variant="ghost"
              size="icon"
              onClick={() => navigate("/settings")}
              className="transition-smooth hover:scale-105"
            >
              <Settings className="h-5 w-5" />
            </Button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="container mx-auto px-4 py-6 space-y-6">
        {/* AI Disclaimer */}
        <Card className="bg-warning/10 border-warning/30 p-4">
          <p className="text-sm text-warning-foreground flex items-start gap-2">
            <span className="text-lg">⚠️</span>
            <span>
              <strong>AI-Generated Insights:</strong> This information is generated by AI. Please review carefully and make informed decisions. Your judgment is important.
            </span>
          </p>
        </Card>

        {/* Financial Overview */}
        <FinancialOverview />

        {/* Goals Section */}
        <GoalsSection />

        {/* AI Insights */}
        <AIInsights />

        {/* Transaction History */}
        <TransactionHistory />

        {/* Quick Action Button */}
        <Button
          className="fixed bottom-6 right-6 h-14 w-14 rounded-full shadow-elevated gradient-hero transition-smooth hover:scale-110"
          size="icon"
          onClick={() => navigate("/add-transaction")}
        >
          <Plus className="h-6 w-6" />
        </Button>
      </main>
    </div>
  );
};

export default Dashboard;
